# Generated by Django 2.2.7 on 2019-12-02 03:31

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_crear_usuario_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disertante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('resumen', mdeditor.fields.MDTextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'disertantes',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', mdeditor.fields.MDTextField(blank=True, default=None, null=True)),
                ('temario', mdeditor.fields.MDTextField(blank=True, default=None, null=True)),
                ('tipo', models.CharField(choices=[('CHARLA', 'CHARLA'), ('TALLER', 'TALLER'), ('CURSO', 'CURSO'), ('OTRO', 'OTRO')], max_length=20)),
                ('publicar', models.BooleanField(default=True)),
                ('pueden_inscribirse', models.BooleanField(default=False)),
                ('inscripcion_abierta', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disertantes', models.ManyToManyField(to='app.Disertante')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
