# Generated by Django 2.2.7 on 2019-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191202_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='disertantes',
            field=models.ManyToManyField(blank=True, to='app.Disertante'),
        ),
    ]
